# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:latest
  amd64: ghcr.io/hassio-addons/base:latest
labels:
  org.opencontainers.image.title: "Snapcast add-on"
  org.opencontainers.image.description: "Snapcast server add-on with Spotify connect support."
  org.opencontainers.image.source: "https://github.com/schmittfelix/hass-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
