# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:15.0.7
  amd64: ghcr.io/hassio-addons/base:15.0.7
  armhf: ghcr.io/hassio-addons/base:15.0.7
  armv7: ghcr.io/hassio-addons/base:15.0.7
  i386: ghcr.io/hassio-addons/base:15.0.7
labels:
  org.opencontainers.image.title: "Snapcast add-on"
  org.opencontainers.image.description: "Snapcast server add-on with Spotify connect support."
  org.opencontainers.image.source: "https://github.com/schmittfelix/hass-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
