# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Snapcast
version: "0.1.2"
slug: snapcast
description: Snapcast server with Spotify connect and Airplay support
url: "https://github.com/schmittfelix/hass-addons/tree/main/snapcast"
audio: true
host_network: true
ingress: true
ingress_port: 1780
panel_icon: "mdi:cast-audio"
privileged:
  - SYS_ADMIN
init: false
arch:
  - aarch64
  - amd64
map:
  - share:rw
host_dbus: true
ports:
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
ports_description:
  1704/tcp: Snapcast client connections
  1705/tcp: Snapcast's control interface
  1780/tcp: Snapcast websocket connections and web-interface
options:
  streams:
    streams: []
  buffer: 1000
  codec: flac
  send_to_muted: false
  sampleformat: "48000:16:2"
  spotify_name: "Frankenstraße"
  log_level: info
schema:
  # Use nested option to force yaml editor on addon's config page
  streams:
    streams: ["str"]
  buffer: int
  codec: list(pcm|flac|vorbis|opus)
  send_to_muted: bool
  sampleformat: str
  spotify_name: str
  spotify_username: str?
  spotify_password: password?
  log_level: list(trace|debug|info|notice|warning|error|fatal)
image: "ghcr.io/schmittfelix/snapcast"
