name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8.0.0
        with:
          stale-issue-message: 'This issue has been inactive for 45 days so will be closed 7 days from now. To prevent this, please remove the "stale" label or post a comment.'
          stale-pr-message: 'This PR has been inactive for 45 days so will be closed 7 days from now. To prevent this, please remove the "stale" label or post a comment.'
          operations-per-run: 100
          # These are the defaults at the time of writing. https://github.com/marketplace/actions/close-stale-issues
          # days-before-stale: 45
          # days-before-close: 7
 
